---
- import_tasks: include-vars.yml

- import_tasks: install-with-package.yml
  when: not certbot_install_from_source

- import_tasks: install-from-source.yml
  when: certbot_install_from_source

- import_tasks: renew-cron.yml
  when: certbot_auto_renew
