---
# tasks file for php-mbstring-patch
- name: Patching mbfilter.h to make it think its installed
  blockinfile:
    path: /usr/include/php/20151012/ext/mbstring/libmbfl/mbfl/mbfilter.h
    insertbefore: '^#define MBFL_MBFILTER_H'
    marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
    block: |
      #undef HAVE_MBSTRING
      #define HAVE_MBSTRING 1

