---

- name: Install yum-plugin-priorities
  package:
    name: yum-plugin-priorities
    state: present

- name: Add the PowerDNS Recursor YUM Repository
  yum_repository:
    name: "{{ pdns_rec_install_repo['yum_repo_name'] }}"
    description: PowerDNS Recursor Repository
    baseurl: "{{ pdns_rec_install_repo['yum_repo_baseurl'] }}"
    gpgkey: "{{ pdns_rec_install_repo['gpg_key'] }}"
    gpgcheck: yes
    priority: 90
    state: present
