---
- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present

- name: Disable SSH Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitUserEnvironment'
    line: 'PermitUserEnvironment no'

- name: Use Only Approved Cipher in Counter Mode
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^Ciphers'
    line: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr'

- name: Set Idle Timeout Interval for User Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^ClientAliveInterval'
    line: 'ClientAliveInterval 300'

- name: Set Idle Timeout Interval for User Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^ClientAliveCountMax'
    line: 'ClientAliveCountMax 0'

- name: Set Permissions on /etc/ssh/sshd_config
  file:
    path: /etc/ssh/sshd_config
    state: file
    mode: 0600
    owner: root
    group: root

- name: Disable X11 Forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'

- name: Set SSH MaxAuthTries to 4 or less
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^MaxAuthTries'
    line: 'MaxAuthTries 6'

- name: Set SSH Banner
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#Banner'
    line: 'Banner /etc/issue.net'

- name: Install Fail2Ban
  apt: state=installed pkg=fail2ban

- name: Reload ssh
  command: /bin/true
  notify:
    - restart ssh
