---
- name: Upgrade APT to the latest packages
  apt: upgrade=dist



- name: Configure ntp - Install Package
  package:
    name: ntp
    state: present



- name: Configure logwatch - Install Package
  package:
    name: logwatch
    state: present

- name: Configure logwatch - Email log summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ abuseio_admin_contact }} --detail high"
              state=present create=yes



- name: Set Permissions on bootloader config
  file:
    path: "{{ grubcfg_location }}"
    state: file
    mode: og-rwx



- name: Set Warning Banner for Standard Login Services
  template: src=common-motd.j2 dest={{ item }} backup=yes
  changed_when: false
  with_items:
    - /etc/motd
    - /etc/issue
    - /etc/issue.net

